business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 6:00 pm
  holidays:
    - January 01, 2019
    - January 13, 2019
    - February 11, 2019
    - March 21, 2019
    - April 29, 2019
    - May 03, 2019
    - May 05, 2019
    - May 06, 2019
    - July 21, 2019
    - September 16, 2019
    - September 23, 2019
    - October 13, 2019
    - November 03, 2019
    - November 24, 2019
    - December 23, 2019
    - January 01, 2020
    - January 12, 2020
    - February 11, 2020
    - March 21, 2020
    - April 29, 2020
    - May 03, 2020
    - May 04, 2020
    - May 05, 2020
    - May 06, 2020
    - July 20, 2020
    - September 21, 2020
    - September 23, 2020
    - October 12, 2020
    - November 03, 2020
    - November 23, 2020
    - December 23, 2020
    - January 01, 2021
    - January 11, 2021
    - February 11, 2021
    - March 21, 2021
    - April 29, 2021
    - May 03, 2021
    - May 04, 2021
    - May 05, 2021
    - July 18, 2021
    - August 11, 2021
    - September 19, 2021
    - September 22, 2021
    - October 10, 2021
    - November 03, 2021
    - November 23, 2021
    - December 23, 2021
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri